version: "3.1"
services:
  database:
    image: postgres:latest
    container_name: octave_backend
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
          - ./.env